version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deno-backend
    ports:
      - '10080:10080'
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/pub-golf
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend
    restart: unless-stopped